## ---------------------------------- ##
##             ddu config             ##
## ---------------------------------- ##

## ++++++++++++++++++++++++++++++++++ ##
##   denops.vim reads in lazy.toml    ##
## ++++++++++++++++++++++++++++++++++ ##

[[plugins]]
repo = 'Shougo/ddu.vim'
depends = 'denops.vim'
on_source = 'denops.vim'
lua_source = '''require('modules.ddu')'''

## ================================== ##
##             ddu-ui-ff              ##
## ================================== ##

[[plugins]]
repo = 'Shougo/ddu-ui-ff'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-source-file_rec'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-filter-matcher_substring'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-kind-file'
on_source = 'ddu.vim'

## ================================== ##
##           ddu-ui-filer             ##
## ================================== ##

[[plugins]]
repo = 'Shougo/ddu-ui-filer'
# depends = ['ddu.vim', 'denops.vim']
on_source = 'ddu.vim'
# lua_add = '''require("modules.ddu.filer-keymap")'''
# lua_source = '''require("modules.ddu.config")'''
# [plugins.ftplugin]
# ddu-filer = '''lua require("modules.ddu.filer-keymap")'''

[[plugins]]
repo = 'Shougo/ddu-source-file'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-column-filename'
on_source = 'ddu.vim'




