
## *************************** ## 
##         lsp config          ##
## *************************** ##
[[plugins]]
repo = 'neovim/nvim-lspconfig'
on_event = ['InsertEnter', 'BufRead']
lua_source = '''require('modules.nvim-lspconfig')'''
